### ISSUE TITLE
Lists of suggested questions for workshops

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#113]
Just recording here the upshot of this morning's discussion with @oliverjam and @yvonne-liu.

Oli will add "suggested questions" for Week 8 workshops, so that if we lollystick contributions from the floor,  nobody will be left stumped for a question to ask.

**Comment by sofer** [comment]
Week 8 is a bit late for us to be switching things up, but getting all students asking questions from the start is so very important. We need to think about it some more.

**Comment by jackherizsmith** [comment]
- [ ] mentors to come up with own questions for workshops

**Comment by sofer** [comment]
@jackherizsmith to facilitate this process with FAC20 and review how we might want to do it in future in a couple of weeks.

**Comment by jackherizsmith** [comment]
- [ ] Work out how to start compiling actual, real FAQs - do we ask mentors to make notes of questions, or do we sit in at the end of workshops?
- [ ] could also track who asked questions to make sure everyone is getting a chance to ask

**Comment by jackherizsmith** [comment]
[Created this document for mentors to collect FAQs](https://docs.google.com/document/d/1KBHvAs5MR8A0a3_X3e1JkC1RsZBGgXiTp_hCPcpYehU/edit?usp=sharing)

- I wonder if we actually need to note who is asking questions, since if one person asks lots of questions but the answer helps everyone that's still of value.

**Comment by oliverjam** [comment]
I think keeping track of exactly who asks each question is a bit much. It's more of a pastoral handover thing where it would be good for whoever is spending the most time in the classroom to alert us if anyone is clearly zooming ahead/struggling/not participating

**Comment by jackherizsmith** [comment]
Re mentors writing down questions - I haven't been able to get Hettie and James to do it this week despite reminders before and after workshops. I will try again with Kat and Chloe next week, otherwise we might actually be better writing our own / revisiting what we're looking to do with this piece of work.

**Comment by jackherizsmith** [comment]
This could have been resolved by #232 ?
