### ISSUE TITLE
Realistic guidance to students on study outside the classroom

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#117]
Is it entirely realistic to say that people do not need to study at all outside the classroom?

There is some degree of integration of new learning or reading ahead of new topics or codewars-style exercises that are likely to be beneficial--and we should articulate it clearly.

**Comment by sofer** [comment]
Potential resources:
- suggested reading
- lists of terms learnt each week (possibly put on a platform like Memrise)

**Comment by jackherizsmith** [comment]
- find and tweak "don't do extra work"

**Comment by sofer** [comment]
See also #143

**Comment by jackherizsmith** [comment]
Hello :wave: I have set up #fac20-revision-circles for anyone interested in connecting with others based on specific material you would like to revise from any of the curriculum so far :books: :nerd_face:

I managed to set the description three times so it's painfully clear what the channel is for :joy: don't hesitate to reach out directly if you'd prefer to be matched up with someone without posting on the channel.

I just want to re-emphasise for what it's worth that there is no expectation to join this channel. Whilst there is clearly a benefit to revising on your own or with others, the course has been designed so that at the end of four months you will be an employable software developer. Founders and Coders has a very high success rate in this regard. This truly is possible working only during class time.

:heart: :heart: Please be kind to yourselves and prioritise your mental and physical health and well-being. I will always be here (on Slack, WhatsApp, etc) to chat and support, whatever and whenever that means :heart: :heart:

**Comment by jackherizsmith** [comment]
- [ ] Create PR to capture guidance
