### ISSUE TITLE
Tech for Better project kick-off slides

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#167]
https://hackmd.io/@fac/HyBg7b-T8#/

Done in response to comments in presentations this afternoon about managing client expectations. Not sure this is complete, but it could be presented first thing on Monday, Week 14.

**Comment by sofer** [comment]
@Albadylic to review and give feedback.

**Comment by Albadylic** [comment]
Would be good to include a slide letting Product Owners know to keep communication via Slack rather than email. 

[This document](https://docs.google.com/document/d/1WMl5-tP6OwenFl_CC9S-AR47KTD8BGABRVUxqmEpLR8/edit) should be adapted to our new timeline and be provided to PO's after expressing interest in the programme.
