### ISSUE TITLE
async/await

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#187]
FAC19 feedback: have we got space to introduce async/await at some point?

**Comment by Albadylic** [comment]
@reubengt has a talk on this

**Comment by reubengt** [comment]
@sofer @Albadylic fac18 had positive feedback, but I'm happy to edit the talk as required.

 In its current form it's a refresher to promises (when it wasn't officially in the curriculum) and introduces async await for the second half of the talk.

Perhaps a workshop would be better for learning in context and identifying common issues when using async await
(function returning a promise for example)

**Comment by oliverjam** [comment]
I would be opposed to trying to fit this in. I think given the struggles students were still having with promises late in the course I would hesitate to add a sugar layer on top. `async` has a lot of potential pitfalls if you don't understand how asynchronous code and promises in JS work properly. They make it quite easy to pretend you're writing sync code, which can cause problems. I elaborated on that in [this blog post](https://oliverjam.es/blog/pitfalls-of-async-functions/).

The main problem in FAC19 was that the group who spiked on "async javascript" ended up talking about `async`/`await` a lot instead of the event loop etc. So they got a sort of semi introduction to it that left them more confused. I'd rather just avoid it entirely by making that spike topic more explicit.

**Comment by sofer** [comment]
I'm going to keep this open just to remind @oliverjam that he needs to re-write the [asnyc spike topic](https://github.com/foundersandcoders/coursebook/blob/master/curriculum/http/spikes.md#async-javascript) to be more explicit.
