### ISSUE TITLE
Review Week 1 GitHub workshop

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#203]
Some in FAC20 found it confusing.

**Comment by sofer** [comment]
Idea from Week 1 SGC:
- engineer deliberate merge conflicts

**Comment by oliverjam** [comment]
I have some ideas on better ways to present this. Feel a little bad I didn't think to look at the week 1 workshops before FAC20 started. I think there are some big improvements to the a11y one we could make too.

I remember most cohorts back in the day would get a whiteboard walkthrough of a basic git flow from the mentors/random alumni wandering through on like Wednesday 😆

**Comment by jackherizsmith** [comment]
#200

**Comment by oliverjam** [comment]
It came up during my team SGC, and I sort of promised to do some kind of screenshare walkthrough of what a "good flow" looks like next week. One concern they had was that by learning all these confusing steps written down they never really had a picture of what was supposed to be happening

**Comment by jackherizsmith** [comment]
Yeah I do think it could do with a clearer visualisation in the workshop. There's time Tuesday morning for a git walkthrough?

**Comment by oliverjam** [comment]
Yeah that might work. I just found a 3 year old screen recording of me deliberately causing then fixing merge conflicts in front of FAC11 😅

**Comment by Albadylic** [comment]
include something on code reviewing PRs in the revised Week 1 git workshop

**Comment by jackherizsmith** [comment]
Relates #311

**Comment by oliverjam** [comment]
Thinking about this a little now. I'll leave some notes here so I don't forget before I actually start working on this.

1. This workshop should focus more on "GitHub workflow in a team" and less on "git CLI commands".
   Everyone on the course inevitably learns how to add/commit/push since they have to do it constantly. Something that has been missing from almost all projects is a focus on writing good commit messages, linking them to issues, creating descriptive PRs, actually reviewing the PRs before merging etc
1. Ideally they should already have learnt the git basics _before_ the course, since that's required to do the application website.

**Comment by sofer** [comment]
@oliverjam to close.

**Comment by oliverjam** [comment]
I reviewed this and made a few tweaks before FAC21 did it. It went a lot better than in previous cohorts; possibly this is because we invested a lot of time and energy into Git/GitHub during the pre-course. Cohorts should come into Week 1 feeling more confident with Git and so get more out of this workshop.
