### ISSUE TITLE
Making the project roles more employer friendly?

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#212]
Currently we have scrum master, DevOps, UI/UX, and QA.

It's possible that junior devs putting the role "scrum master" on their CV may not be helping their cred as a developer. Even using the phrase "QA" may be sending subtle signals to some employers that this candidate cannot really code. It's hard to be sure how much  of an effect this is, but it may be worth reviewing the roles and refocusing them on activities that are more obviously useful to an early-career developer.

**Comment by jackherizsmith** [comment]
@sofer check [these slides](https://hackmd.io/@fac/B1AL4V3ML#/7) since they asked at SGC for more structured roles, and we came up with this compromise: #205 facilitating people taking responsibility for important aspects of making great projects, without roles being explicitly named.

The current plan is to go through these before lunch tomorrow alongside issue management, and then remind teams of the four areas again on Wednesday morning.

**Comment by sofer** [comment]
@sofer and @jackherizsmith to discuss.
