### ISSUE TITLE
Crazy 8s from Week 2 or 3

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#215]
FAC19 feedback

**Comment by sofer** [comment]
Week 3: @Albadylic to do a miniature design sprint on Wed 11:00-11:30.

**Comment by jackherizsmith** [comment]
This could be creating unnecessary additional work but could we perhaps introduce a different ideation technique each week, to give people lots of tools to choose from? I was slightly concerned when someone asked about learning Figma at A&R's talk, since it's just a tool that probably has better alternatives and it might be better in general for us to be officially tool-agnostic / encourage students to explore for themselves.

So from searching crazy eights, I've found a few more exercises [here](https://blog.prototypr.io/how-to-generate-diverse-ideas-in-30-minutes-7a4196e7d6ce) or [here](https://medium.com/@Ian_Moritz/4-favorite-brainstorming-processes-da22d632561d).

**Comment by Albadylic** [comment]
I like this idea and I also like the idea that students could compose their own Design Sprints by being shown various exercises that they learn across different weeks / during Design Week.

I have two concerns:
- Time - projects are stretched for time as is the schedule for the first half
- Space to gain experience - I think to know which exercises and tools you may like to use takes time to practice which each. Figma is a good choice for prototyping as it's _free_ and it _allows clickable prototypes_ whereas other tools like Whimsical have limits on the number of workspaces & does not allow movement between frames.

**Comment by Albadylic** [comment]
These articles have proved very helpful, thanks @jackherizsmith !

**Comment by sofer** [comment]
Slide deck linked from coursebook. Ready to close.
