### ISSUE TITLE
Update week 2 project assessment criteria re hiding API keys?

### ISSUE THREAD

**Issue by jackherizsmith** [foundersandcoders/coursebook#223]
Am I right in understanding that it's not possible to hide API keys when deploying on GitHub Pages?

**Comment by oliverjam** [comment]
You're right, this is really confusing. It's not GitHub Pages, it's any client-side code. If your code runs in the browser any value it accesses is visible to anyone who knows how to open devtools.

The only thing you can do is hide the key from the source code on GitHub, which I guess makes it a tiny bit harder for people to find it. It also means you can use a GitHub API key, since they automatically revoke those if they detect them in your repo 😅 

We should remove the project criteria and instead add a not explaining this concept. My recommendations for projects would be 1) use an API with no key or 2) use a free API so losing the key doesn't mean anything
