### ISSUE TITLE
Add team code walk-through to default schedule

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#225]
5:15 on Thursday for 30 minutes, perhaps (wk2 SGC feedback)

**Comment by jackherizsmith** [comment]
I'm not 100% clear what this means - time for teams to talk each other through how the code works, ask questions etc? Would this be mandatory or strongly advised?

**Comment by sofer** [comment]
@jackherizsmith  to lead on this and consult with @oliverjam

**Comment by oliverjam** [comment]
I would rather encourage them to be doing this constantly throughout the project, but maybe that's unrealistic. I'm not sure we ever give any guidance on how they should collaborate, so that might be something to add early-on.

E.g. each pair should make a PR detailing their changes and how they work. The other pair should review the PR, check they understand the code and ask questions if they don't. Only then should they merge the PR.

I think what really happens is pairs make PRs with a useless title and no description, then the other pair blindly merges without reading the changes. Not sure how to reconcile the time-constraints of a 2 day project with a more realistic code review practice.

**Comment by jackherizsmith** [comment]
Great point. We can spend some time revisiting PR best practice, so that one pair always requests someone from the other pair, and that other pair read the changes together and ask any questions they have before it's merged?

**Comment by oliverjam** [comment]
Yeah I think a demonstration of "good teamwork practices" would be more helpful than the current GitHub workshop early on

**Comment by oliverjam** [comment]
Actions:
- continue with 17:15 Thursday slot for the team to review their code as a group.
- include something on code reviewing PRs in the revised Week 1 git workshop #203
