### ISSUE TITLE
Intro to student projects

### ISSUE THREAD

**Issue by jackherizsmith** [foundersandcoders/coursebook#240]
Would be good to schedule some time to talk to FAC20 about student projects and lay out the plan.

**Comment by jackherizsmith** [comment]
@Albadylic and @jackherizsmith to meet Monday 3 Aug to discuss

**Comment by Albadylic** [comment]
@jackherizsmith and I discussed and have written up [this document](https://hackmd.io/@fac/r1e1qsrbv) to guide CF's in the process. Will be merged into CF documentation in due course. For now, the next action is for Jack to present to students next week. Closing the issues since the process is outlined
