### ISSUE TITLE
Notes for curriculum mentors to write own intro presentations

### ISSUE THREAD

**Issue by jackherizsmith** [foundersandcoders/coursebook#257]
I think the best way forward is to tell curriculum mentors what 5-10 points they need to cover over their 20-minute presentation, and then leave it to them to make their own presentations.

It will engage them much more in their week's topic and schedule, ensure they're prepared to explain things covered in the presentation, and ultimately presenting someone else's slides always comes across a bit weird.

It would require some work to create the guidance for each of the weeks (including React week?)

**Comment by oliverjam** [comment]
I'm not convinced this is a good idea (which is why I wrote new presentations for most of the weeks). The presentations should be part of the curriculum, and contain the right introductory information we want them to be thinking about presented in a way that's appropriate.

Presentations kind of started as an optional way for mentors to inject some personality and introduce themselves, but I think they're too important for setting the stage for the week's learning to leave up to mentors who may have varying levels of time/energy to commit.

Maybe we could ask mentors to do 2 or 3 slides introducing themselves that could be presented _before_ they give our official topic intro?

**Comment by jackherizsmith** [comment]
Yeah that works.

**Comment by jackherizsmith** [comment]
Action: JAck to look into how HAckMD can be editted by others

**Comment by oliverjam** [comment]
@jackherizsmith don't know if you got anywhere with this but I ended up building https://fac-slides.netlify.app/ for my Intro JS workshop at the meetup this week. The code is here https://github.com/oliverjam/fac-slides. It's a pretty basic Eleventy website that generates slides from a markdown file in the `slides/` directory.

Authoring uses the same markdown/slides format as Reveal.js/HackMD (using `---` as a separator). It's a lot more minimal than Reveal though—the slides are just in a big horizontally scrolling container with scroll-snap. There's a tiny bit of client-side JS enhancement for keyboard navigation and the progress bar.

I think we could leverage Netlify's branch preview deploys for mentors making changes. The core "unbranded" material lives in markdown on `main`, then if the mentors for a week want to jazz it up they can clone, make a branch, then present using the Netlify preview. If the changes are useful enough to be permanent we can merge it, otherwise it's a throwaway branch just for that cohort.

**Comment by jackherizsmith** [comment]
I got as far as thinking they could just prepare their own separate slides but this sounds much better!
