### ISSUE TITLE
Review of prerequisites

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#285]
Overdue.

**Comment by sofer** [comment]
Some resources worth looking at:
- https://scrimba.com/. Co-founded by Per (FAC4). Impressive. There are some good free resources already available on the platform, but we can also create our own. See e.g. [The Coding Bootcamp Primer](https://scrimba.com/learn/bootcampprimer).
- https://www.executeprogram.com/. Notable for its use of spaced repetition. Several relevant courses. The free tier allows one new lesson per day, which is probably the best cadence for getting the best use of the repetition. Somewhat addictive.
- https://www.khanacademy.org/. An entirely free platform with a good [Computing](https://www.khanacademy.org/computing/) section. Notable for its support for teachers to create their own classrooms and monitor student progress.

**Comment by Albadylic** [comment]
Reflections:
- fCC is a good resource but gives limited practical knowledge. Easy to _hack_ it to pass the tests without understanding. Lacking in repetition.
- Image Carousel, most folks seem to follow tutorials so we may want to find something else.
- Improve GitHub hosting tutorials
- Learning how to problem solve
- Learning to work in teams and social skills
- List of recommended katas and what to use to solve them (e.g. these 3 use Array.map, these 4 use Array.reduce)
- What are the prereq's and what are they for? Aim is to make sure people aren't lost when they are on the course. Big gap between starting to engage with code and joining the course - probably bigger than from starting the course to finishing. Improving first-touch introduction to coding.
- Fundamental understanding of coding is missing. 
- Coaching is likely to be our most consistent revenue stream. We ought to line up our coaching programme with our prereq's.
- Review of what we're presenting people with and perhaps to rely less on external resources and create our own instead.
- Scrap fCC before FAC22
- Video series could be an interesting approach to make code more accessible to beginners (what is a var, why declare a function...)
- Two concepts: prereq's / learning (learning to code) & course requirements / applying (justifying you are ready for the programme)
- Practical guidance on how to find solutions rather than waiting for help

**Comment by oliverjam** [comment]
My suggestion from today's circle:

- split the concept of "pre-requisites" from "learning to code"
  - **Requirements**: the application process that proves you're ready for the course
  - **Learning**: an absolute-beginner-focused curriculum where anyone can learn the basics of HTML/CSS/JS from scratch

**Comment by Albadylic** [comment]
Action: Gregor to add thoughts here before next circle

**Comment by Albadylic** [comment]
## Some thoughts
(I hope these are helpful and sorry if they're too lucid to make sense)

- free Code Camp provides a good introduction but not a solid (unshakeable) foundation. The main benefit is that we can see people have completed it.
- Execute Program may be a good alternative but I'm not sure you can see other's progress. Coachees liked it. 
- We might like to introduce repl.it as a resource. A big thing I've noticed amongst my coachees is that they know how to solve the problems on fCC and Codewars but are missing some of the fundamentals - in particular, what is a function, what can we use it for and how do we call them vs define them.
- Almost everything we suggest is text based - we ought to consider other formats to improve accessibility (some applicants have mentioned preferring videos to understand material).
- Applicants should complete fCC _before_ moving to codewars (feedback from coachees)
- We might like to break down the pre-req's into multiple pages/stages - e.g. the theory (fCC); practice & algorithms (CWs); build (Website); project (image carousel).
- Image carousel project seems to be getting stale and most people seem to rely heavily on tutorials. Could we offer multiple project options that encourage more unique approaches?
- There's a large part missing around social skills and social rules - how to work in diverse teams; recognising your biases; pairing, talking about your code...

**Comment by oliverjam** [comment]
## Dan & Oli discussion

- What should the path into FAC look like?
- We currently have a rough 3 stage structure:
   1. Learning fundamentals (currently fCC)
   1. Practicing/consolidating (currently CW)
   1. Practical application of your learnings (currently website/carousel)
- Oli wants to split part 1 (learning fundamentals) out so they're not required for applications
   1. Learning (optional, would start with fCC but maybe transition to better material over time)
   1. Assessment (mandatory to apply for FAC; set of CW style problems plus a practical project)
- Application would be based on learning outcomes. Part 1 is where you _learn_ them, part 2 is where you _demonstrate_ you have learnt them
- Potential benefit of the current prereqs: there is a certain barrier to entry where people have to prove their commitment by spending a bunch of their free time ticking boxes on fCC. If it's too quick/easy to get to the application stage we'll possibly get more people who aren't actually that dedicated
   - This is possibly better solved with policy changes around the application window. E.g. insisting on Expression of Interest before the application window opens.

Action: @oliverjam to draft a list of learning outcomes we want people to have met before they can join FAC.
Actions: General Circle to discuss potential changes to application windows/expression of interests so people can't parachute into the program right before the window closes.

**Comment by oliverjam** [comment]
## Outcome from @sofer and @oliverjam discussing this morning


### Actions

1. Start work on the new curriculum
   - Decide on high-level language learning outcomes
   - Map these to separate "features" around a challenge
   - Pick a platform (e.g. repl.it importing GitHub repo)
1. Pick a list of mandatory kata to replace current CW requirement
1. Amend website learning outcomes/requirements
   - Merge image carousel in
We don't like how freeCodeCamp presents HTML, CSS & JS as totally independent things to be learnt in their entirety in isolation. Our ideal curriculum would have learning outcomes broken down into sections based on _features_. It's more interesting (and possibly more useful) to learn language features in context—i.e. learn about the button element, how to style it and how to make it do something when clicked in one "module".

- Eventual goal is to have an applicant curriculum of material that teaches sets of learning outcomes based around practical features.
   - Rather than the fCC model of "learn all of HTML in isolation, then learn all of CSS in isolation...".
   - Instead

**Comment by oliverjam** [comment]
These changes are now live on the website, and announced to applicants on Slack/with a post on the site.
