### ISSUE TITLE
Week 9 topics

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#342]
> Real-world project (4 one-day workshops on different topics but working towards a single overaching project all week)

See https://github.com/foundersandcoders/coursebook/issues/288#issuecomment-746578159

Is one of those one-day workshops going to be on Next.js with hosting on Vercel?

**Comment by oliverjam** [comment]
I wasn't planning on it. Not sure how I feel about going directly from introducing React to an even more abstracted meta-framework. It would definitely be more "real world" I guess

**Comment by oliverjam** [comment]
Having thought about this more I am reconsidering. Might need further thought before we start creating Week 9 content

**Comment by oliverjam** [comment]
We're going to use this issue to track ideas for the new Week 9.

**Comment by oliverjam** [comment]
I would basically like this week to be a "stuff you realistically need in a production app you get paid money for", since we don't have time for those things in React Week.

1. Testing (shifted from React Week to make room for intro SPA stuff)
1. Integrating with a backend/API
1. Deploying the frontend/backend (same git repo? serverless? 3rd party DB?)
1. Planning a full-stack build (frontend first with mock backend)

Teach Next will kind of cover quite a few of those, so might be a good idea. Would possibly require a bit of an intro to what serverless functions are, since that's how Next's "API routes" are structured (i.e. you don't manage an actual server with routing etc).

Testing _may_ have been covered already if we end up teaching Cypress earlier on, since they can just keep E2E testing their app without changing anything much.

**Comment by Albadylic** [comment]
In terms of naming, does Week 9 remain 'React Week' even if (the former) React week's content is split across week 8 (App) and Week 9?

**Comment by oliverjam** [comment]
Probably not. We've made all the other week names more generic (API Week instead of Express Week, which means we can drop Express from Week 7 entirely and not have to change the name). So Week 8 should probably be Single-Page App Week, and Week 9 Production App or Full-stack App or something?

**Comment by sofer** [comment]
@redahaq and @reubengt might be interested in helping out with Next.js, if needed.

**Comment by reubengt** [comment]
100% on board✨

**Comment by oliverjam** [comment]
That would be great! I'd also be interested in your opinions on what's missing from the curriculum to bridge the gap from React Week to "deploying an actual product". Anything we didn't cover in the thread above?

**Comment by Albadylic** [comment]
To Discuss: how teams work in weeks 7, 8, 9. Groups will be together for the three weeks, in the past React Week projects have been done in pairs. Is there a way to tie all three weeks together?

**Comment by oliverjam** [comment]
I'm going to have a think about how these weeks will fit together

**Comment by sofer** [comment]
Next week:
- start with testing React + Next.js + DB
- finish workshops by Tues lunchtime
- Tue pm project spikes (like last week)
- Main unsolved problem is which DB service to use
- Check in with @reubengt for Next.js support

Over to @oliverjam

**Comment by reubengt** [comment]
I can be in the space wednesday/thursday to help out with projects. re databases, is the idea to introduce a new database service? I'm not sure what has been discussed already but just throwing an idea out there, would firebase work? I have found it much easier to use firebase for a small project than setting up a postgres database.

**Comment by sofer** [comment]
Ha ha! @reubengt you have just wandered into the week's great debate :-) Great to know that you are around Wed/Thurs.

**Comment by oliverjam** [comment]
@reubengt I've just had a lot of bad experiences with the Firebase ecosystem. Didn't enjoy it much on Aplisay and I've seen several FAC grads get really stuck in a tangled mess trying to build out a TFB project that started with Firebase.

The idea is that if they're doing a Next app deployed to something like Vercel (or other serverless-first service) then they can't have their own stateful server for something like Postgres. So they'll need an externally hosted data-persistence layer—and it's a lot faster to use a 3rd party one than build your own.

I was thinking AWS DynamoDB is the most obvious "default hosted DB". Otherwise [FaunaDB](https://fauna.com/) is great (although it has a weird query language).

**Comment by sofer** [comment]
@oliverjam I love what you have done with Week 9 and I am looking forward to the presentations on Friday.

**Comment by oliverjam** [comment]
For posterity I ended up just creating 4 Postgres DBs on AWS RDS and giving each group their connection string. They spent Monday working through the official Learn Next.js tutorial, then the rest of the week building a project.

Feedback:
1. "Learn Next.js is long and boring and has lots of copy/pasting".  
I think this is fine, since part of the goal here was to ease the cohort into learning via real-world resources and not our Coursebook. We could maybe think about breaking it up with other stuff so it's not a full day.
2. "The project criteria was really hard".  
I didn't expect this—I think I misjudged how difficult they would find it to adapt the Next.js examples from Monday into their own thing. This mostly comes from a lack of conceptual understanding I think; they haven't had a chance to fully absorb what is going on and so everything feels like a complex new thing.  
We probably need more guidance on the shopping basket feature, since groups tried to do that in a ton of different ways, some more successfully than others. Possibly dedicated spike time on Tuesday afternoon (as we did in Week 7).

**Comment by oliverjam** [comment]
Circle discussion: we'd like to try a similar project-based week for FAC21 too. We'll make some tweaks:
1. Spikes like Week 7 on e.g. shopping baskets to give them a little more guidance. Do this on Monday to break up the long Next.js workshop
2. Interview prep on Monday to also break up the workshop
