### ISSUE TITLE
API week (May 4-7) to be 4 days

### ISSUE THREAD

**Issue by Oliversw** [foundersandcoders/coursebook#367]
Due to being interrupted by a bank holiday. Creating this issue as a reminder of deciding on this during the FAC21 Circle today. 

Friday April 9th of the second reading week is still open if there is anything necessary that could be delivered earlier than API week however

**Comment by oliverjam** [comment]
We are shifting Express intro forward to Week 4, so we can afford to lose a day here for this cohort. We can fill it with something else (Docker?) for future cohorts

**Comment by oliverjam** [comment]
Okay so having thought about next week more I have some thoughts.

1. I'd forgotten we were losing a day, so reducing the amount of workshops is ideal
2. The REST API project is kind of weird, especially after they just spent 3 weeks learning how to do session-auth, validation, error-handling etc.
3. It would be nice to make this project the "culmination" of all the server-side stuff before they start doing everything client-side in React.

So my suggestions are:

- Drop the Express intro workshops since they've done that.
- Keep the middleware workshop from Monday, since they haven't covered how to make their own middleware with Express yet.
- Massively simplify the REST API workshop so it fits into a 2-hour slot
   - If this isn't the main project it doesn't need to cover so much stuff
   - E.g. there's a big complex section on auth that isn't necessary
- Add a workshop on something like server-side validation/error-handling
   - Show how to use session cookies to communicate validation errors etc after form submissions
- Make the project a more general "Build a proper server-rendered site with all the stuff you haven't managed to do in previous weeks"

This will give them a chance to consolidate their knowledge and really practice the "doing it properly" part, since there aren't really many big new concepts for them to implement.
