### ISSUE TITLE
Interviewing apprentice candidates

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#371]
First draft.

https://www.notion.so/foundersandcoders/e76378cd566546a88c2a8ca29a4988a1

Intended for circulation to employers and candidates.

**Comment by sofer** [comment]
Also, this probably belongs in the apprenticeship guide, but I do want to get the eyes of the curriculum circle on it.

**Comment by oliverjam** [comment]
I like it. My only suggestion would be to add a reminder that they ideally shouldn't judge candidates on what they _know_ at this moment. Instead they should be trying to assess their capacity to learn and improve. (Current knowledge is kind of irrelevant since they're about to embark on a bootcamp)

**Comment by sofer** [comment]
Thank you both. Updated.
