### ISSUE TITLE
Decide on content for first day back

### ISSUE THREAD

**Issue by Oliversw** [foundersandcoders/coursebook#389]
Developers are prepared to come back on the Friday of reading week 2. We currently don't have content prepared but mentioned that it could be a good chance to get them back together and working on some code before jumping into the rest of the course.

**Comment by oliverjam** [comment]
We have decided to run this like the one-day projects at the end of the course. d3.js was suggested as a topic—@oliverjam to go away and try to think of other potential options by the end of the week.

**Comment by oliverjam** [comment]
[copied from Discord]

I've been looking at alternatives to d3.js for the Friday at the end of the break.

I think it might be fun to do one of Wes Bos' [JavaScript30](https://javascript30.com) projects, since a lot of them use interesting different browser APIs (e.g. canvas for drawing, speech recognition/synthesis, geolocation etc).

1. It's nice to give them a sense of how powerful a web app can be (without even needing external libraries)
2. It'll get them practicing their JS (lots of these APIs use promises, but it's not more boring "fetch pokemon")
3. It's pretty fun/not too serious and the resources already exist for free

I think the fun part is important—this is the point where they've got some fundamentals down and need to be inspired a bit to generate passion. Just doing the same boring forms and fetching over and over isn't great :sweat_smile:

We could either pick a single one for them all to focus on, or give them a subset of a few that we think are good.

@sofer what do you think?

**Comment by sofer** [comment]
@oliverjam *"I think the fun part is important"*, is a sentiment I can agree with. I am also in favour of giving them a shortlist of projects. Are we going to ask them to work in 2s or 4s?

**Comment by oliverjam** [comment]
I think pairs, since I'm a little concerned that some people haven't been getting enough hands-on practice in the groups of 4. There also isn't a _huge_ amount to do on most of these. If you follow along with Wes' video it's probably <1 hour, so it might be best if we just provide a minimal intro to the Web API in question and let them struggle a bit.
