### ISSUE TITLE
Shift Wednesday morning challenge forward to Tuesday at 4.

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#411]
Employment prep is needed for at least some of FAC21, but might be better off at the end of the day on Wednesday instead of the middle of the afternoon on Tuesday. This would create a gap that could be filled the Wednesday morning challenge. This would also mean that in future, when employment prep may no longer be needed, Wednesdays and Thursdays would be entirely given over to projects.

**Comment by oliverjam** [comment]
Circle discussion:

We're not 100% sure why we want to shift employment prep to Wednesday. Could you elaborate on that @sofer?

Ideally we'd like to keep the morning challenge where it is, since Mon/Tue are already quite intense with 4 hours of workshops teaching new concepts per day. It's important to break those up a bit (e.g. spikes on Mon, interview prep on Tue). Moving the morning challenge to Tue afternoon would make that day really intense. The challenges are supposed to be quite hard and a bit frustrating, which works as a brief warm up before projects but would probably be more negatively received if it came after an already tough day of workshops.

**Comment by sofer** [comment]
Closing.
