### ISSUE TITLE
Authentication week resources (HTB)

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#470]
Hack the Box: https://www.hackthebox.eu/

Also, is there any virtue in renaming this "security" week and also ensuring that both the speakers are giving security-related talks?

**Comment by oliverjam** [comment]
We don't really cover anything to do with actually securing a computer/server. That's one of the things that I think is beyond the scope of the course. Especially since we rely on platform-as-a-service providers like Heroku/Netlify, who handle all of that for us.

If we were getting them to deploy bare metal servers then this would be important, but we'd probably have to drop any frontend/user-facing dev work and become a backend/devops only course 🙃
