### ISSUE TITLE
A short Web science curriculum, perhaps

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#475]
Anni has suggested developing a series of sessions, perhaps 6 x 1 hour, for FAC22. It might fit well into one morning a week in the latter half of the programme while they are working on projects.

**Comment by oliverjam** [comment]
I think we could use a general "lecture slot" for giving the cohort information that doesn't directly relate to the week topic. We've discussed putting that first thing on Wed, before the morning challenge and projects.

**Comment by sofer** [comment]
Provisionally looking at 10-12 30-minutes sessions on a Wednesday morning. @sofer to set up initial conversation with @Intersticia and @oliverjam.

**Comment by oliverjam** [comment]
Here's a list of stuff I think would be useful to cover (much of it inspired by [Tom Scott's The Basics](https://www.youtube.com/playlist?list=PL96C35uN7xGLLeET0dOWaKHkAlPsrkcha) YouTube series.

- Computer electronics
   - Binary
   - Switches
   - Logic gates/boolean logic
   - Machine code
- Computer science
   - Algorithms
   - Big O/time & space complexity
   - Cryptograph/hashing/encryption
   - Text encoding: ASCII/UTF-8/UTF-16
   - Text compression
- World Wide Web
   - The internet protocol stack: MAC/IP/TCP/HTTP
   - URLs -> domains -> DNS -> IP addresses
   - HTTPS encryption
- Ethics
   - Consequences/impact (e.g. civil engineers learn about the [Hyatt Regency disaster](https://en.wikipedia.org/wiki/Hyatt_Regency_walkway_collapse))
   - Obvious flaws missed by homogenous teams
   - Building safe social platforms
   - Algorithmic bias in machine learning/AI
   - How to not build a global platform for political disinformation and genocide
   - Employment rights & unions
- Security
   - How hacking works
   - White hat vs black hat
   - Famous exploit examples (e.g. [Samy](https://en.wikipedia.org/wiki/Samy_(computer_worm)))
   - Basics of protecting your sites

**Comment by Intersticia** [comment]
Hey there Oli,

How about you and I set up some times over the next few weeks to do some curriculum development together?  

I’m pretty good from 8 am your time most days except Wednesdays (when I can do after 10 am), Thursdays (before 11 am your time) and Fridays (after 10 am your time).

Let me know what might suit on your end.

Very much looking forward to this!

Anni

**Comment by oliverjam** [comment]
Notes from my call with @Intersticia:

- Probably time for 5 lectures
- Structured as a history
- Computing -> information sharing (networks)
- Where did we come from?
- Going right back—what is a computer? Women were the original computers.
- What is the affordance of digital? What does it allow you to do? Quantum?
- HyperText/protocols/web sitting on top of that.
   - Building for the web: Web 1/2.0/semantic web. Blockchain? Provenance/ownership/sustainability.
   - Leads in to security
- Business models
- Ethics. "Just because you can doesn't mean you should". Case studies (death.io?).
- Do we want them to do research etc within the session in small groups?

Actions: @Intersticia is going to come up with a structure that fits into our 1 hour slot on Wednesday mornings. We don't necessarily have to run this from Week 1. There are ~5 hours worth of material, so could be towards the latter half of the course.
