### ISSUE TITLE
.env files and the dotenv node module - cover this explicitly in a workshop?

### ISSUE THREAD

**Issue by reubengt** [foundersandcoders/coursebook#570]
FAC22 and FAC23 have run into the same issue of not knowing how to import environment variables. 

https://learn.foundersandcoders.com/workshops/node-postgres/

This workshop creates a .env file with a script but doesn't explain that the dotenv module is what actually reads that file.

I don't think it needs to be a separate workshop, can just be an added line of explanation into what happens with the .env file?

**Comment by oliverjam** [comment]
Yeah thanks for raising this.

So I amended this workshop last cohort to use a DB setup script, because basically all cohorts before spent up to an hour messing around with Postgres instead of actually using the DB with Node.

The env var stuff is explained in the [connecting to the database](https://learn.foundersandcoders.com/workshops/node-postgres/#connecting-to-the-database) section. However it is inside the (collapsed by default) "More info about the connection string" box. Maybe nobody expands these "helpful info" boxes? 😅 

I guess an easy change would be to expand it by default. Maybe _all_ of these across all workshops should be expanded by default (if we think nobody opens them 😭 )

**Comment by reubengt** [comment]
I did not see this! I think maybe the confusion is that while scrolling down it looks like a heading and not something you can click to open. (even though the solutions and hints have the same green box UI) 

Maybe we should set just the "extra information" type boxes to open by default. Easy to miss imo, especially when your brain is so busy reading new material😅

**Comment by oliverjam** [comment]
@oliverjam to make info box expanded by default
