### ISSUE TITLE
More time for responding to code review

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#599]
Feedback from FAC23 this week: 

> Would have liked to have an hour in the schedule to address issues on Friday morning after code review. In my team I think we found that we didn't need two hours for sprint review and presentation prep. 

Do we want to shift the schedule around to give more time for responding to code review?

There may also be an opportunity in the pre-apprenticeship to do introduce a quick response session at the start of the following week's session after the project. Would we have time for it?

**Comment by oliverjam** [comment]
This is particularly applicable to the longer-term apprenticeship projects. 8 days worth of work with only an hour to address feedback. We could try moving code review to the Thursday, since there's more time available on the longer projects.

It would also be nice even on the shorter projects. This would have the added benefits of forcing teams to have their projects deployed and ready to review earlier.

**Comment by sofer** [comment]
Are we happy to close this now?
