### ISSUE TITLE
Mentor Schedule for FAC25

### ISSUE THREAD

**Issue by reubengt** [foundersandcoders/coursebook#684]
Keeping https://github.com/foundersandcoders/tasks/issues/212 in mind, delegating programme delivery to the mentors keeps the CF available to do internal work (whatever is necessary i.e platform development, curriculum stuff, etc)

For FAC25 I think we should aim for mentors being in Tuesday-Thursday

![Image](https://user-images.githubusercontent.com/42008435/175311930-f4409b3d-9f01-4987-8481-7a0da477df09.png)

New responsibilities are 
Tuesday
1.  Facilitate discussion of workshops
2. Help debug during projects
3. Introduce projects

Wednesday
1. Facilitate Spike Presentations
2. Support Project Work

Thursday
1. Support Project Work
2. Code Review

Friday
Optional, attend presentations if they can

**Comment by Albadylic** [comment]
Yes!

**Comment by sofer** [comment]
This also relates to #630 and #691, because what mentors are needed for and when will be affected by what is being delivered and when. 

Given that mentoring support is given voluntarily, we need to be very mindful of the mentors' time. 

Back in the day, at Palmers Road, we used to have "Office hours" towards the end of the day, when programme graduates working upstairs would come down and help people downstairs in the classroom. How about if we set aside 5-6pm on Tuesday (start of project), Wednesday (mid-project) and Thursday (code review) for mentor support? See also https://github.com/foundersandcoders/coursebook/issues/630#issuecomment-1157400378.

If we reformulate the tech spike as being an integral part of the project #691, then end of the day on Tuesday will work pretty well in terms of timing.

Looking at the proposed responsibilities above, I'm not entirely sure if:
- for facilitating discussion of workshops, it is more important to have somebody good at facilitating discussions or good at responding to technical questions, in other words do we want somebody who is an experienced facilitator with a bit of technical nous or somebody who is technically expert;
- having advice on tap all day to support project work is a good idea;
- the facilitator should be delegating things like introducing the project?

**Comment by reubengt** [comment]
I don't think we should reduce mentor time, its very clear from the mentor feedback linked below that it's a fantastic learning opportunity for mentors, and also incentivises them to come back later on!

https://airtable.com/appVcgmqIfy3K4z2w/tblpUImZn5fevPn8y/viw5JBiip5OJt0sNc?blocks=hide
https://airtable.com/appX9k4VBlILtoFmL/tblrRM4ugbpWe9tsN/viw7GF0NibYrcky7r?blocks=hide

**Comment by Albadylic** [comment]
We can close this, we've emailed employers with the commitment
