### ISSUE TITLE
Keep an eye on Deno

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#686]
https://deno.land/ and https://deno.com/.

See also for Ryan's pitch at Remix Conf 2022 https://youtu.be/pBcFJmQ6UVM

**Comment by oliverjam** [comment]
I've pretty much replaced Node with Deno for all personal stuff these days. If I were teaching someone to code from scratch I would consider Deno first as it doesn't have a lot of Node's baggage. I'm not sure that it would be a good idea for FAC yet though, since you would bypass getting experience in the whole Node/npm ecosystem, package management etc that is super important to the kinds of jobs our grads go into.

**Comment by sofer** [comment]
Also:
- https://astro.build/
- https://xstate.js.org/
