### ISSUE TITLE
Review of application guidance and projects

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#715]
A few things bugged me about the applications this time:
- Thin commit histories
- Default commit messages
- Forgetting to publish content on GH pages
- Linking to repos instead of published pages from within published pages 
- Uninteresting websites
- Cut-and-paste code

I also think the projects may not be helping. The fruit shop in particular seemed to be victim to a fair amount of cut-and-pastery.

I would like to propose two solutions:

1. That we provide a short checklist of things-to-do-and-not-do in projects and to link to it at the top of every project (or resources) page, so that there is no excuse for some of the things we have been seeing.

2. Every term change **_exactly one_** of our projects, based on which project gave us least useful feedback about the candidates.

Also, I am still as keen as I ever was on using [180 websites in 180 days](https://jenniferdewalt.com/) as inspiration for the projects.

**Comment by sofer** [comment]
Instead of a checklist of dos and don'ts, something like these instructions might work better:
1. Create a new repo with the name _'fac-one'_ (or _'fac-two'_, _'fac-three'_, etc.)
2. Create an empty `index.html` page and commit it with the commit message, _'Empty index page'_
3. Publish the repo to GitHub Pages
4. In index.html, create a link to you previously-published project (unless this is your first project repo) and commit it with the commit message, _'Link to previous project website'_
5. Add a link to your new project repo on https://account.foundersandcoders.com/apply/projects. 
6. Keep committing code, a little at a time, and don't use the default commit messages, always compose your own, so that your commit history tells a step-by-step story of how you created your project.

**Comment by Albadylic** [comment]
For next term, replace the fruit shop with a new challenge. Give a data array with a series of objects - the project is to build a front-end which allows the user to visualise and manipulate the data.

**Comment by Albadylic** [comment]
- [ ] Be clearer that the fruit shop should be managed with an object
- [ ] Valid email on comment box
- [ ] Ability to submit more than one comment using comment box
- [ ] Deploy all projects to GitHub pages and include the deployed links
- [ ] Link to deployed sites and not GitHub repos
- [ ] Committing often and commit messages tell a story
- [ ] Following a journey through the websites, it should be a good UX for us when we review them.

Applications should show us someone's learning journey, but equally they should be a usable portfolio site. Links to deployed sites, as well as GitHub repo's should be featured. And there should be a consistent theme or implementation across the projects.

It's an opportunity to show off, everyone should aim to impress us rather than only just meeting the requirements.

Each project should have a clear purpose which can be summarised in a sentence or two. The requirements should be an extension of this and not a number of other detailed steps.
---

Fixes #714
