### ISSUE TITLE
Update schedule for 4 day week - including final projects

### ISSUE THREAD

**Issue by Albadylic** [foundersandcoders/coursebook#722]
Moving to a 4-day week for final projects might be a challenge. Especially this term, where we're taking Mondays as a non-contact day.

In Design Week, the context is shaped in the first days with Discovery / Definition workshops.

For build weeks, dropping a day would likely mean the project scope reduces.

If we do drop to a 4-day staff week, do we still expect dev's to be doing the course 5-days?

**Comment by Albadylic** [comment]
Nothing to do this term, figure out next term

**Comment by ByteSizedIT** [comment]
Pulled forward to current Sprint () from Sprint 20 / End of Term

(Linked to #758 - review of handbook for references to 5 day week, to be completed following this issue (722) at end of term)

**Comment by ByteSizedIT** [comment]
Created branch [four-day-week](https://github.com/foundersandcoders/coursebook/tree/four-day-week) which:

- Creates week '0 - Introduction', including Course Intro and Server Intro sessions on the Thurs, and Server Workshop on the Fri; 
- Moves each day's schedule forward one day during weeks 1-12 (i.e. Mondays becoming Fridays, Tuesdays becoming Mondays etc); 

- TODO: Decide how to manage the 'first' day of 'Design Weeks' - currently scheduled in on 'contactless' Fridays.

**Comment by ByteSizedIT** [comment]
Created branch [four-day-week-2](https://github.com/foundersandcoders/coursebook/tree/four-day-week-2), copied from the [four-day-week](https://github.com/foundersandcoders/coursebook/tree/four-day-week) branch before addressing the TODO in comment above.

To this end I have pushed the schedules for both Design Week’s (7 and 10) back one day, so that they run Monday-Fri again, rather Fri to Mon. This means that:
- The first day for each Design week is in person
- The Fridays before each Design week (i.e. the Fridays in Weeks 6 and 9) are now empty in the schedule
- The first day of build for each project, previously pulled forward to the Fridays in weeks 7 and 10) have been lost

I have then moved around the existing schedule within Design week to enable Fridays to be remote / contactless once more.

Compared to FAC25, as a result of the changes above In-house Design Week has:
- 15mins less Portfolio Documentation time
- No Alumni Speaker
- No Spike presentation
- 15mins extra time for the actual Spike
- 4hrs 30mins (10%) less build time over the project, dropping from 44hrs 25mins to 39hrs 55

Compared to FAC25, as a result of the changes above TfB Design Week has:
- No Spike presentation (but the same amount of time for the Spike)
- 4hrs 30ins (10-12%) less build time over the project, dropping from 43hrs 55mins to 39hrs 25 

This is a sizeable drop in build time for both projects, and therefore a starting point for discussion in terms of whether anything else can be removed from Design weeks to allow for more Build, or whether the schedule can be shuffled in another way. 

If either of the empty days remain as so, they could potentially be used for other items discussed separately, including the introduction of end-to-end testing and/or a Large Code base task (issue #737). Noting that they are both non-contact days in terms of the format this allows.

**Comment by Albadylic** [comment]
- Missing link for server intro
- Friday before design week could be a consolidation, or portfolio building day, or some kind of self-assessment
- Move all feedback surveys to Friday mornings?

### Design Week
- Fridays are not facilitated, so we can remove check-ins [I'm assuming we're not expecting them to be accountable to each other]
- Friday of Design Week (in-house and TFB), let's aim for something that can be completed solo (portfolio building, project documenting, tech spikes). Can we move sprint planning to the Friday (45 mins), taking time out of Code Planning?

### Tech for Better
- Can we extend the TFB project to finish on a Friday, and make an exception to our staff 4-day week? [I feel like a Friday is a good day for showcase and party]
- Do we want to shift the usability testing & synthesis to be at 14:00 on the Tuesday? FAC25 seemed to feel they wanted more time wireframing and checking in with their PO's.
- I'm not sure the week is effective in it's current state, there's a lot of time spent code planning and tech spiking. However, it might be that all this time is needed to explore their projects properly and get a sense of what they'll complete, to set expectations with their PO.

**Comment by Albadylic** [comment]
Outcomes of discussion:
- Consolodation / portfolio day on Friday of week 6 (and week 3 (?) )
- Term finishes on a Thursday

**Comment by ByteSizedIT** [comment]
> * Missing link for server intro

Done

> * Friday before design week could be a consolidation, or portfolio building day, or some kind of self-assessment

Relabelled Fridays before each design week (i.e weeks 6 and 9) as 'Consolidation day', as per week 3 (before client-side app)

> * Move all feedback surveys to Friday mornings?

Moved feedback surveys to Friday mornings during Design weeks. Left other weeks in the old slot on Thursdays for now.

> * Fridays are not facilitated, so we can remove check-ins [I'm assuming we're not expecting them to be accountable to each other]

Removed

> * Friday of Design Week (in-house and TFB), let's aim for something that can be completed solo (portfolio building, project documenting, tech spikes). Can we move sprint planning to the Friday (45 mins), taking time out of Code Planning?

To confirm, Sprint Planning is already scheduled for Friday, and Code Planning is scheduled on Thursday during In-house Design week and Wednesday during TfB week. 
Thinking is that Sprint Planning should come after both Code Planning and Tech Spikes, so I have left it on the Friday for now.
Assumption is that project teams will be working together on Fridays during the 3 week projects, allowing Sprint Planning and Build time to be scheduled there?

> * Can we extend the TFB project to finish on a Friday, and make an exception to our staff 4-day week? [I feel like a Friday is a good day for showcase and party]

Discounted by Dan during Curriculum Circle, with reduced Build time during TfB accepted as a consequence.

> * Do we want to shift the usability testing & synthesis to be at 14:00 on the Tuesday? FAC25 seemed to feel they wanted more time wireframing and checking in with their PO's.

Additional 30 min Wireframe Review session with PO added on Thursday AM, followed by 2hr 30 wireframing pulled forward from the session that was after user testing. User Testing and Synthesis sessions moved to the PM, followed by a wireframing session reduced down to 45mins 


> * I'm not sure the week is effective in it's current state, there's a lot of time spent code planning and tech spiking. However, it might be that all this time is needed to explore their projects properly and get a sense of what they'll complete, to set expectations with their PO.

To review following experience/feedback from FAC25. If able to reduce Code Planning, perhaps pull everything forward to allow some of the lost Build time to be added back in during the Fri afternoon.

**Comment by ByteSizedIT** [comment]
> > * I'm not sure the week is effective in it's current state, there's a lot of time spent code planning and tech spiking. However, it might be that all this time is needed to explore their projects properly and get a sense of what they'll complete, to set expectations with their PO.
> 
> To review following experience/feedback from FAC25. If able to reduce Code Planning, perhaps pull everything forward to allow some of the lost Build time to be added back in during the Fri afternoon.

Reduced code planning by 1hr45 to 3hr45; Split /reduced tech spike by 15min to 2hr45; Moved sprint planning to Thursday; As a result claimed 2 hours build time back.

**Comment by ByteSizedIT** [comment]
Updated overview....


Compared to FAC25, the In-house Project in the [draft schedule ](https://github.com/foundersandcoders/coursebook/tree/four-day-week-2) now has:
* 3hrs 55mins less build time than FAC25 (down from 44hrs 25mins to 40hrs 30mins)

This has been reduced from a full day by the following changes to In-house Design Week:
* No Alumni Speaker (prev 45mins)
* No Spike presentations / presentation prep  (prev 1hr 15)
* 15mins extra time for the actual Spike (now 2hrs)
* 15 mins less Portfolio Documentation time (now 30mins)
* 35 mins less time for check in and feedback survey (removed duplicates and Friday checkins)
* 5 mins less in Cohort SGC


Compared to FAC25, the TfB Project now has:
* 2hrs 25mins less build time than FAC25 (down from 44hrs 10mins to 41hrs 45mins)

This has been reduced from a full day by the following changes to TfB Design Week:
* 1hr 45 less Code Planning (down from 5hr 30 to 3hr 45 )
* 15 mins less for Tech Spike (down from 3hrs to 2h 45)
* No Spike presentations / presentation prep

**Comment by ByteSizedIT** [comment]
Actions:
Remove checkouts from Fridays
Move feedback forms from Thursdays to Fridays
Bring Sprint planning forward to the Thursday on In-house Design week (reduce Code Planning and SGC for space)

**Comment by ByteSizedIT** [comment]
Curriculum Circle: agreed to merge four-day-week-2 branch in to main
