### ISSUE TITLE
"Maybe we could focus more on the code in code reviews"

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/coursebook#764]
From SGC today:  _"A lot of the code reviewing that goes on is more like manual interface testing than reviewing the actual code. Is there any way that we could address this?"_

Looking at [our guidance on code reviewing](https://learn.foundersandcoders.com/course/handbook/code-review/), it looks like people may be focusing on the first five bullet points:

- Open the repo on GitHub and read the readme
- Open the deployed version and play around with the UI
- Does the project meet the user stories for that week?
- Does it demonstrate the learning outcomes for that week?
- Can you see any obvious bugs or areas to improve?

and ignoring the last four:

- Does the file structure make sense?
- Can you you follow the different paths the code might take?
- Do variables and functions have clear and descriptive names?
- Do you understand the code?

What can we do about this?

**Comment by Albadylic** [comment]
- We need a more structured approach: 'Follow every one of these 9 bullet points and add an issue against each one'
- @ivanmauricio to record an intro to code review
- Introduce to both FAC25 and FAC26 in this way
- We've extended code review on the full-time programme to 90 mins, let's review if this feels right at end of term
- We could be asking people to report on the projects akin to the [Project Report](https://learn.foundersandcoders.com/course/handbook/project-documentation/) i.e. one issue with a longer report rather than separate small issues. _Code Reporting_ (?)

Relates #739

**Comment by sofer** [comment]
FAC26. We will set up a "project-review" repo with an issue template that outlines 9 topic headings and set it for homework.

**Comment by sofer** [comment]
We did it. Twice. Scored ave 4.55/5 in Week 8 and 4.73/5 in Week 8 from 11 responses. ⭐ ⭐ ⭐ ⭐ ⭐

**Comment by sofer** [comment]
I will make sure we start this from Topic 1 for FAC27
