### ISSUE TITLE
Change background of course book to light yellow

### ISSUE THREAD

**Issue by octaviacogher** [foundersandcoders/coursebook#915]
- Amend course book background so light yellow or light blue so it is dyslexia friendly

**Comment by camelPhonso** [comment]
@octaviacogher - 

Tried adjusting the background to a yellow tinge but it actually came out too strong. Guidance on dyslexia accessibility indicates yellow and blue as good colours for the background under black lettering so I used a light blue shade.

I'm very conscious of too many aesthetic changes creating a particular look for FAC so I tried to make adjustments as subtle as possible while still having a positive effect for accessibility. This is what it currently looks like in the new branch I have created for this issue:

<img width="932" alt="Screenshot 2023-10-02 at 14 47 13" src="https://github.com/foundersandcoders/coursebook/assets/114600712/23843c75-ea74-41d3-a2b6-a639c54964ca">
- The background is now a light blue shade to make reading text more comfortable
- Highlights are now a yellow box around the text (they were previously a white box)
- The striped box here is formed of thinner lines, also blue, but there is the option of removing the stripes entirely

Like so:
<img width="729" alt="Screenshot 2023-10-02 at 14 51 52" src="https://github.com/foundersandcoders/coursebook/assets/114600712/997ca8d0-c954-40fe-b103-f1edd5985772">

Other changes:
- Selected text on the sidebar is now highlighted in pure black instead of the previous dark blue (this is standard guindance on accessibility for dyslexia)
- The dividing line between menus is a slightly darker grey for better contrast
<img width="718" alt="Screenshot 2023-10-02 at 14 59 19" src="https://github.com/foundersandcoders/coursebook/assets/114600712/9cca6360-8817-438c-9141-db7370fd34f5">

**No functionality has been changed in this branch**

I would probably advise on upping the font size as well, but that hasn't been changed in the screenshots above. Standard guidance is to use 14point to 16point font size, which would be 18.6px (to equate 14 point). That would look like this:
<img width="975" alt="Screenshot 2023-10-02 at 15 09 36" src="https://github.com/foundersandcoders/coursebook/assets/114600712/440d777e-9197-43ee-9ac2-5c0ebbfe7d9d">

The difference may not be terribly perceptible here, but it cramps up the page a bit more.

You can see these changes by fetching the ```dyslexia-accessibility``` branch
